# Generated by Django 2.2.17 on 2020-11-14 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('pub_date', models.DateField(default=datetime.date.today)),
                ('postImage', models.ImageField(upload_to='images/')),
                ('body', models.CharField(max_length=300)),
            ],
        ),
    ]
